---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev
  namespace: dev-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
# krateo bff crds
- apiGroups:
  - widgets.ui.krateo.io
  resources:
  - cardtemplates
  resourceNames:
  - card-dev-1
  verbs:
  - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev
  namespace: dev-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  dev
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io
